# Generated by extendr: Do not edit by hand
# nolint start

#' @usage NULL
#' @useDynLib lavaanrust, .registration = TRUE
NULL

#' Fit the covariance-only one-factor DWLS slice used by GenomicSEM's
#' `commonfactor()` model.
#'
#' `sample_cov` and `wls_v` are flattened column-major R matrices.
#' @param sample_cov Flattened observed covariance matrix.
#' @param wls_v Flattened DWLS weight matrix.
#' @param n Number of observed variables.
#' @param max_iter Maximum optimizer iterations.
#' @param tol Convergence tolerance.
#' @export
fit_one_factor_dwls <- function(sample_cov, wls_v, n, max_iter, tol) .Call(wrap__fit_one_factor_dwls, sample_cov, wls_v, n, max_iter, tol)

#' Fit a covariance-only observed-variable DWLS model where the free parameters
#' are selected entries of `vech(Sigma)`.
#'
#' This covers the common-factor null model and the parameter-table refit used
#' to estimate its residual-covariance Q statistic.
#' @param sample_cov Flattened observed covariance matrix.
#' @param wls_v Flattened DWLS weight matrix.
#' @param free_mask Integer mask over `vech(Sigma)`.
#' @param fixed_values Fixed values over `vech(Sigma)`.
#' @param n Number of observed variables.
#' @export
fit_observed_covariance_dwls <- function(sample_cov, wls_v, free_mask, fixed_values, n) .Call(wrap__fit_observed_covariance_dwls, sample_cov, wls_v, free_mask, fixed_values, n)

#' Fit the marker-scaled common-factor GWAS DWLS slice used by
#' GenomicSEM's `commonfactorGWAS()` model.
#'
#' Variable order is expected to be `SNP, trait_1, ..., trait_k`.
#' @param sample_cov Flattened observed covariance matrix.
#' @param wls_v Flattened DWLS weight matrix.
#' @param k Number of trait indicators.
#' @param max_iter Maximum optimizer iterations.
#' @param tol Convergence tolerance.
#' @export
fit_commonfactor_gwas_dwls <- function(sample_cov, wls_v, k, max_iter, tol) .Call(wrap__fit_commonfactor_gwas_dwls, sample_cov, wls_v, k, max_iter, tol)

#' Fit the common-factor GWAS Q-model refit where direct SNP effects and trait
#' residual variances are free and all first-stage quantities are fixed.
#' @param sample_cov Flattened observed covariance matrix.
#' @param wls_v Flattened DWLS weight matrix.
#' @param loadings Fixed marker-scaled trait loadings.
#' @param gamma Fixed factor regression coefficient.
#' @param direct Initial direct SNP effects.
#' @param residuals Initial trait residual variances.
#' @param psi Fixed factor residual variance.
#' @param phi Fixed SNP variance.
#' @param k Number of trait indicators.
#' @param max_iter Maximum optimizer iterations.
#' @param tol Convergence tolerance.
#' @export
fit_commonfactor_gwas_q_dwls <- function(sample_cov, wls_v, loadings, gamma, direct, residuals, psi, phi, k, max_iter, tol) .Call(wrap__fit_commonfactor_gwas_q_dwls, sample_cov, wls_v, loadings, gamma, direct, residuals, psi, phi, k, max_iter, tol)

#' Fit the fixed-measurement one-factor GWAS DWLS slice used by the default
#' `userGWAS(..., fix_measurement = TRUE)` path.
#' @param sample_cov Flattened observed covariance matrix.
#' @param wls_v Flattened DWLS weight matrix.
#' @param loadings Fixed marker-scaled trait loadings.
#' @param residuals Initial trait residual variances.
#' @param psi Initial factor residual variance.
#' @param gamma Initial factor regression coefficient.
#' @param phi Initial SNP variance.
#' @param k Number of trait indicators.
#' @param max_iter Maximum optimizer iterations.
#' @param tol Convergence tolerance.
#' @export
fit_user_gwas_fixed_measurement_dwls <- function(sample_cov, wls_v, loadings, residuals, psi, gamma, phi, k, max_iter, tol) .Call(wrap__fit_user_gwas_fixed_measurement_dwls, sample_cov, wls_v, loadings, residuals, psi, gamma, phi, k, max_iter, tol)

#' Evaluate generic RAM-model implied covariance and Jacobian surfaces.
#'
#' Row indices are 1-based to match R. Operator codes are:
#' `1 = =~`, `2 = ~`, `3 = ~~`.
#' @param lhs_index Parameter-table lhs row indices.
#' @param rhs_index Parameter-table rhs row indices.
#' @param op_code Parameter-table operator codes.
#' @param free_index Free-parameter indices, with `0` for fixed rows.
#' @param fixed_values Fixed row values, ignored for free rows.
#' @param free_values Current free-parameter values.
#' @param observed_index Observed-variable indices in the full RAM system.
#' @param free_row_offsets Offsets into `free_row_indices` for each free parameter.
#' @param free_row_indices Flattened 1-based row indices grouped by free parameter.
#' @param n_variables Number of variables in the full RAM system.
#' @export
evaluate_ram_surfaces <- function(lhs_index, rhs_index, op_code, free_index, fixed_values, free_values, observed_index, free_row_offsets, free_row_indices, n_variables) .Call(wrap__evaluate_ram_surfaces, lhs_index, rhs_index, op_code, free_index, fixed_values, free_values, observed_index, free_row_offsets, free_row_indices, n_variables)

#' Compile immutable generic RAM-model structure into a reusable native plan.
#' @param lhs_index Parameter-table lhs row indices.
#' @param rhs_index Parameter-table rhs row indices.
#' @param op_code Parameter-table operator codes.
#' @param free_index Free-parameter indices, with `0` for fixed rows.
#' @param fixed_values Fixed row values, ignored for free rows.
#' @param observed_index Observed-variable indices in the full RAM system.
#' @param free_row_offsets Offsets into `free_row_indices` for each free parameter.
#' @param free_row_indices Flattened 1-based row indices grouped by free parameter.
#' @param lower_bounds Lower bound for each free parameter.
#' @param upper_bounds Upper bound for each free parameter.
#' @param n_variables Number of variables in the full RAM system.
#' @export
compile_ram_dwls_plan <- function(lhs_index, rhs_index, op_code, free_index, fixed_values, observed_index, free_row_offsets, free_row_indices, lower_bounds, upper_bounds, n_variables) .Call(wrap__compile_ram_dwls_plan, lhs_index, rhs_index, op_code, free_index, fixed_values, observed_index, free_row_offsets, free_row_indices, lower_bounds, upper_bounds, n_variables)

#' Check whether a generic RAM native plan still points at live Rust state.
#'
#' External pointers are intentionally not serializable across all R worker
#' strategies, so the R layer can rebuild them lazily when needed.
#' @param plan Native plan external pointer.
#' @export
ram_dwls_plan_is_valid <- function(plan) .Call(wrap__ram_dwls_plan_is_valid, plan)

#' Fit a generic RAM-model DWLS slice from a reusable native plan.
#'
#' @param plan Native plan external pointer from `compile_ram_dwls_plan()`.
#' @param sample_cov Flattened observed covariance matrix.
#' @param wls_v Flattened DWLS weight matrix.
#' @param free_values Initial free-parameter values.
#' @param max_iter Maximum optimizer iterations.
#' @param tol Convergence tolerance.
#' @param compute_se Whether to compute naive standard errors from the final bread matrix.
#' @export
fit_ram_dwls_plan <- function(plan, sample_cov, wls_v, free_values, max_iter, tol, compute_se) .Call(wrap__fit_ram_dwls_plan, plan, sample_cov, wls_v, free_values, max_iter, tol, compute_se)

#' Fit a generic RAM-model DWLS slice from compiled row data.
#'
#' This compatibility entry point rebuilds a native plan for one-off callers.
#' Repeated fits should prefer `compile_ram_dwls_plan()` plus
#' `fit_ram_dwls_plan()`.
#' @param sample_cov Flattened observed covariance matrix.
#' @param wls_v Flattened DWLS weight matrix.
#' @param lhs_index Parameter-table lhs row indices.
#' @param rhs_index Parameter-table rhs row indices.
#' @param op_code Parameter-table operator codes.
#' @param free_index Free-parameter indices, with `0` for fixed rows.
#' @param fixed_values Fixed row values, ignored for free rows.
#' @param free_values Initial free-parameter values.
#' @param observed_index Observed-variable indices in the full RAM system.
#' @param free_row_offsets Offsets into `free_row_indices` for each free parameter.
#' @param free_row_indices Flattened 1-based row indices grouped by free parameter.
#' @param lower_bounds Lower bound for each free parameter.
#' @param upper_bounds Upper bound for each free parameter.
#' @param n_variables Number of variables in the full RAM system.
#' @param max_iter Maximum optimizer iterations.
#' @param tol Convergence tolerance.
#' @param compute_se Whether to compute naive standard errors from the final bread matrix.
#' @export
fit_ram_dwls <- function(sample_cov, wls_v, lhs_index, rhs_index, op_code, free_index, fixed_values, free_values, observed_index, free_row_offsets, free_row_indices, lower_bounds, upper_bounds, n_variables, max_iter, tol, compute_se) .Call(wrap__fit_ram_dwls, sample_cov, wls_v, lhs_index, rhs_index, op_code, free_index, fixed_values, free_values, observed_index, free_row_offsets, free_row_indices, lower_bounds, upper_bounds, n_variables, max_iter, tol, compute_se)

# nolint end
