# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.get_V_full <- function(k, V_LD, varSNPSE2, SE_SNP, I_LD, varSNP, GC, coords, i) {
    .Call(`_GenomicSEM_get_V_full`, k, V_LD, varSNPSE2, SE_SNP, I_LD, varSNP, GC, coords, i)
}

